export const LOAD_TODOS = 'LOAD_TODOS';
export const LOAD_TODOS_SUCCESS = 'LOAD_TODOS_SUCCESS';

export const ADD_TODO = 'ADD_TODO';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';

export const UPDATE_TODO = 'UPDATE_TODO_SUCCESS';

export const DELETE_TODO = 'DELETE_TODO_SUCCESS';

export const CLEAR_TODOS = 'CLEAR_TODOS';